### ISSUE TITLE
Proper Commit Messages

### ISSUE THREAD

**Issue by GitauHarrison** [AlvaroIsrael/AlvaroIsrael#1]
Hi @AlvaroIsrael 

Consider [this guide](https://chris.beams.io/posts/git-commit/#imperative) when writing your commit messages

**Comment by AlvaroIsrael** [comment]
Hey @GitauHarrison, thanks for the tip! I will considerer the article in future commits. Another great tip would be https://www.conventionalcommits.org/en/v1.0.0/, maybe you can  check it out later! I have started to follow you for support! Have a nice day!
